#!/usr/bin/with-contenv bash
s6-setuidgid root

# expose local sockets om användaren vill
if [ "${enable_local:-false}" = "true" ]; then
    echo "Local API enabled, exposing sockets"
    socat TCP-LISTEN:50800,reuseaddr,fork UNIX-CONNECT:/tmp/TelldusClient &
    socat TCP-LISTEN:50801,reuseaddr,fork UNIX-CONNECT:/tmp/TelldusEvents &
fi

echo "Starting telldusd"
exec /usr/sbin/telldusd --nodaemon
